### PR TITLE
rgadded

### PR DESCRIPTION
**Pull request by UbedMohammed**
resource added

### CODE REVIEW

**Comment by UbedMohammed** [comment]
Hi Kashif and Rajinder, please approve this as it is updated

**Review by rajindersin85 — APPROVED** [review]
Approved

**Review by mkashif3 — CHANGES_REQUESTED** [review]
please select location as central india.

**Review by rajindersin85 — APPROVED** [review]
Approved

**Review by mkashif3 — CHANGES_REQUESTED** [review]
change India to india

**Review by rajindersin85 — APPROVED** [review]

**Review by mkashif3 — APPROVED** [review]
approved

**Pull request merged**
