### PR TITLE
Feature.kashif

### PR DESCRIPTION
**Pull request by mkashif3**
adding new RG. Please approve.

### CODE REVIEW

**Comment by mkashif3** [comment]
Hi Rajinder and Ubed, please approve the request to add RG.

**Review by rajindersin85 — APPROVED** [review]
fine

**Review by UbedMohammed — CHANGES_REQUESTED** [review]
please change location to us region

**Review by rajindersin85 — APPROVED** [review]
looks fine

**Review by UbedMohammed — APPROVED** [review]
5n

**Pull request merged**
